import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AdminWrapper } from "@/components/tableContext/page";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "../providers";
export const metadata: Metadata = {
  title: "Learn2Code",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AdminWrapper>{children}</AdminWrapper>
        </Providers>
      </body>
    </html>
  );
}
